const WeatherCategoryIcons = Object.freeze({
    CLEAR: { day: "wi-day-sunny", night: "wi-night-clear" },
    A_FEW_CLOUDS: { day: "wi-day-cloudy-high", night: "wi-night-alt-cloudy-high" },
    PARTLY_CLOUDY: { day: "wi-day-sunny-overcast", night: "wi-night-alt-partly-cloudy" },
    MOSTLY_CLOUDY: { day: "wi-day-cloudy", night: "wi-night-cloudy" },
    OVERCAST: { day: "wi-cloudy", night: "wi-cloudy" },
    SNOW: { day: "wi-day-snow", night: "wi-night-alt-snow" },
    RAIN_SNOW_MIX: { day: "wi-day-rain-mix", night: "wi-night-alt-rain-mix" },
    RAIN_ICE_MIX: { day: "wi-day-rain-mix", night: "wi-night-alt-rain-mix" },
    FREEZING_RAIN: { day: "wi-day-rain", night: "wi-night-alt-rain" },
    RAIN_FREEZING_RAIN_MIX: { day: "wi-day-rain-mix", night: "wi-night-alt-rain-mix" },
    FREEZING_RAIN_SNOW_MIX: { day: "wi-day-rain-mix", night: "wi-night-alt-rain-mix" },
    ICE: { day: "wi-day-sleet", night: "wi-night-alt-sleet" },
    SNOW_ICE_MIX: { day: "wi-day-rain-mix", night: "wi-night-alt-rain-mix" },
    LIGHT_RAIN: { day: "wi-day-showers", night: "wi-night-alt-showers" },
    RAIN_FOG_MIX: { day: "wi-day-rain", night: "wi-night-alt-rain" },
    RAIN: { day: "wi-day-rain", night: "wi-night-alt-rain" },
    SHOWERS_IN_VICINITY: { day: "wi-day-showers", night: "wi-night-alt-showers" },
    THUNDERSTORM: { day: "wi-day-thunderstorm", night: "wi-night-alt-thunderstorm" },
    THUNDERSTORM_IN_VICINITY: { day: "wi-day-lightning", night: "wi-night-alt-lightning" },
    TORNADO: { day: "wi-tornado", night: "wi-tornado" },
    TROPICAL_STORM: { day: "wi-hurricane", night: "wi-hurricane" },
    WINDY: { day: "wi-day-windy", night: "wi-night-alt-cloudy-windy" },
    CLOUDY_WINDY: { day: "wi-day-cloudy-windy", night: "wi-night-alt-cloudy-windy" },
    OVERCAST_WINDY: { day: "wi-cloudy-windy", night: "wi-cloudy-windy" },
    DUST: { day: "wi-dust", night: "wi-dust" },
    SMOKE: { day: "wi-smoke", night: "wi-smoke" },
    HAZE: { day: "wi-day-haze", night: "wi-night-fog" },
    HOT: { day: "wi-hot", night: "wi-stars" },
    COLD: { day: "wi-snowflake-cold", night: "wi-snowflake-cold" },
    BLIZZARD: { day: "wi-snow-wind", night: "wi-snow-wind" },
    FOG: { day: "wi-day-fog", night: "wi-night-fog" },
});

export default WeatherCategoryIcons;